version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: savestateform
      MYSQL_USER: savestateform
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d  # Mount the entire folder
